import { Analytics } from "@vercel/analytics/react"
import { Inter } from "next/font/google"
import "./globals.css"
import NavBar from "./nav"
import { Providers } from "./providers"
import Script from "next/script"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="mx-auto max-w-sm bg-white p-6 dark:bg-black md:max-w-2xl lg:max-w-4xl xl:mt-10 xl:max-w-6xl">
            <NavBar />
            {children}
          </div>
        </Providers>
        <Analytics />
      </body>
      <Script src="/analy.js" />
    </html>
  )
}
